# See claude code environment variables documents at https://code.claude.com/docs/en/settings
[env]

[tools]
claude = "latest"
python = "3.12"
ruff = "latest"
uv = "latest"

# === Tasks
[tasks.venv-create]
description = "âœ¨ Create Python virtual environment (.venv)"
run = "uv venv"

[tasks.venv-remove]
description = "ðŸ’¥ Remove Python virtual environment folder (.venv)"
run = "rm -r .venv"

[tasks.inst]
description = "ðŸ’¾ Install Python dependencies (dev, test, doc, etc.) via uv"
run = "uv sync --all-extras"

[tasks.app]
description = "ðŸš€ Run Streamlit app locally"
run = ".venv/bin/streamlit run app.py"
