[env]
# See claude code environment variables documents at https://code.claude.com/docs/en/settings

[tools]
claude = "latest"
python = "3.12"
ruff = "latest"
uv = "latest"

# === Tasks
[tasks.venv-create]
description = "‚≠ê Create project virtual environment (.venv)"
run = "uv venv"

[tasks.venv-remove]
description = "üí• Remove project virtual environment completely"
run = "rm -r .venv"

[tasks.inst]
description = "Install Python dependencies (dev, test, doc, ...)"
run = "uv sync --all-extras"

[tasks.app]
description = "Run streamlit app"
run = ".venv/bin/streamlit run app.py"
